### ISSUE TITLE
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 127)

### ISSUE THREAD

**Issue by sugizo** [thomasahle/sunfish#102]
```
$ uname -a
Darwin sugizo.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64

$ git clone https://github.com/thomasahle/sunfish
$ cd sunfish

$ tools/fancy.py -cmd ./sunfish.py
Traceback (most recent call last):
  File "/Users/sugizo/Downloads/sunfish/tools/fancy.py", line 284, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/sugizo/Downloads/sunfish/tools/fancy.py", line 234, in main
    engine = await load_engine_from_cmd(args.cmd, debug=args.debug)
  File "/Users/sugizo/Downloads/sunfish/tools/fancy.py", line 40, in load_engine_from_cmd
    _, engine = await chess.engine.popen_uci(cmd.split())
  File "/Users/sugizo/Downloads/test0/lib/python3.9/site-packages/chess/engine.py", line 2681, in popen_uci
    await protocol.initialize()
  File "/Users/sugizo/Downloads/test0/lib/python3.9/site-packages/chess/engine.py", line 1429, in initialize
    return await self.communicate(UciInitializeCommand)
  File "/Users/sugizo/Downloads/test0/lib/python3.9/site-packages/chess/engine.py", line 1094, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 127)
```

**Comment by codethief** [comment]
I'm seeing the same issue using Python 3.10.6 on Linux.

**Comment by sugizo** [comment]
```
git clone https://github.com/thomasahle/sunfish
cd sunfish
python ./sunfish.py
```

**result**
no error occured, just loading on terminal

**expected result like on github readme**
```
$ tools/fancy.py -cmd ./sunfish.py
Playing against sunfish 2023.
Do you want to be white or black? black
  1 ♖ ♘ ♗ ♔ ♕ ♗ ♘ ♖
  2 ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙
  3
  4
  5
  6
  7 ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
  8 ♜ ♞ ♝ ♚ ♛ ♝ ♞ ♜
    h g f e d c b a

Score: 23, nodes: 11752, nps: 13812, time: 0.9
 My move: d4
  1 ♖ ♘ ♗ ♔ ♕ ♗ ♘ ♖
  2 ♙ ♙ ♙ ♙   ♙ ♙ ♙
  3
  4         ♙
  5
  6
  7 ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟
  8 ♜ ♞ ♝ ♚ ♛ ♝ ♞ ♜
    h g f e d c b a

Your move (e.g. c6 or g8h6): Nf6
```

**Comment by codethief** [comment]
@sugizo

> **result**
> no error occured, just loading on terminal

What do you mean by "just loading"? Also, which Python version (on which OS) are you using?

**Comment by thomasahle** [comment]
Unfortunately `sunfish.py` can't use `env`, since it needs the `-u` argument added to python.

Regrading default values for namedtuple, I believe that requires Python 3.7.

**Comment by yirod3721** [comment]
so what do we do now

**Comment by codethief** [comment]
@thomasahle Maybe you could specify the Python versions Sunfish runs with, using e.g. a [.tool-versions](https://github.com/asdf-vm/asdf) file?

**Comment by sugizo** [comment]
```
$ uname -a
Darwin sugizo.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
$ python -V
Python 3.9.13
```

just loading means 
no error occured, 
but no respond either, 

loading is the loading animated on top of terminal is rounding

**Comment by julupanter** [comment]
Same problem here.
I don't know how to fix it yet.

**Comment by julupanter** [comment]
> Same problem here. I don't know how to fix it yet.

Solved. 

`sudo apt install pypy3`

run with pypy3 in front:

`tools/fancy.py -cmd ./sunfish.py`

**Comment by sugizo** [comment]
not work too when tested on google colab
**steps**
```
!apt install -y pypy3
!git clone https://github.com/thomasahle/sunfish
```

**execute**
`!cd sunfish && python ./sunfish.py`

**result same like tested on mac**
just loading means
no error occured,
but no respond either,

loading is the loading animated on top of terminal is rounding

**execute**
`!cd sunfish/tools/fancy.py -cmd ../sunfish.py`

**result**
/bin/bash: line 0: cd: too many arguments

**Comment by codethief** [comment]
@julupanter Which version of PyPy did you install exactly?

**Comment by HelixPiano** [comment]
Ran into the same issue. Had to downgrade python from 3.14 to 3.9.18 and install pypy3.9 to get it working.

**Comment by thomasahle** [comment]
Fixed on master: the root cause was the `#!/usr/bin/env pypy3` shebang failing with exit code 127 wherever pypy3 isn't installed. `sunfish.py` now uses a polyglot sh header that runs `pypy3` when available and falls back to `python3` (thanks @zserge for the technique). The old `-u` concern is moot — all UCI output has long been explicitly flushed. So `tools/fancy.py -cmd ./sunfish.py` now works with only python3 installed. Thanks everyone for the debugging in this thread; please reopen if current master still fails.
