### ISSUE TITLE
Does not run on my iMac

### ISSUE THREAD

**Issue by doronby** [thomasahle/sunfish#110]
tools/fancy.py -cmd ./sunfish.py
Python 3.11.2
macOS Monterey

Output : 

dby@dorons-imac sunfish-master % tools/fancy.py -cmd ./sunfish.py
Traceback (most recent call last):
  File "/Users/dby/Downloads/sunfish-master/tools/fancy.py", line 284, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/dby/Downloads/sunfish-master/tools/fancy.py", line 234, in main
    engine = await load_engine_from_cmd(args.cmd, debug=args.debug)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dby/Downloads/sunfish-master/tools/fancy.py", line 40, in load_engine_from_cmd
    _, engine = await chess.engine.popen_uci(cmd.split())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chess/engine.py", line 2681, in popen_uci
    await protocol.initialize()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chess/engine.py", line 1429, in initialize
    return await self.communicate(UciInitializeCommand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chess/engine.py", line 1094, in communicate
    return await command.result
           ^^^^^^^^^^^^^^^^^^^^
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 127)

**Comment by Hamster-lord** [comment]
it happens to me too

**Comment by Hamster-lord** [comment]
but it says: "Unable to locate engines.json file."

**Comment by forthrin** [comment]
Me three. Then again it could just be Python dependency hell, which basically has ruined the whole language.

**Comment by thomasahle** [comment]
Try `tools/fancy.py -cmd ./sunfish.py -debug`.
For me, the issue was that it couldn't find `pypy3`.
It's an issue with python shebangs, that you can't specify a fall-back python version. Currently sunfish.py uses `#!/usr/bin/env pypy3`.

**Comment by forthrin** [comment]
Wasn't harder than that... What a beautiful chessboard made only of ANSI codes and Unicode characters :)

`$ find . -name '*.py' -exec perl -i -pe 's/env pypy3/env python3/' {} +`

**Comment by thomasahle** [comment]
Closing as a duplicate of #102 — same root cause: the `#!/usr/bin/env pypy3` shebang fails when pypy3 isn't installed. Workaround until that's fixed: change the shebang to `python3`, or install pypy3.
